CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'primary key',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name VARCHAR(255) COMMENT 'User Name',
  email VARCHAR(255) UNIQUE COMMENT 'User Email',
  picture VARCHAR(255) COMMENT 'User Picture'
) default charset utf8mb4 COMMENT '';

CREATE TABLE sodas (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  stock INT DEFAULT 0,
  image_url TEXT,
  creatorId VARCHAR(255) NOT NULL,
  FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS `user`;

-- CREATE TABLE keeps(
--   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
-- updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
-- name VARCHAR(255) NOT NULL,
-- description VARCHAR(1000) NOT NULL,
-- img VARCHAR(1000) NOT NULL,
-- views INT UNSIGNED NOT NULL DEFAULT 0,
-- creatorId VARCHAR(255) NOT NULL,
-- FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE
-- )

DROP TABLE cart_items;

CREATE TABLE cart (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  creatorId VARCHAR(255) NOT NULL,
  user_id INT REFERENCES accounts(id) ON DELETE CASCADE,
  is_checked_out BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE

);
CREATE TABLE cart_items (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  cart_id INT NOT NULL,
  soda_id INT NOT NULL,
  creatorId VARCHAR(255) NOT NULL,
  FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE,
  FOREIGN KEY (soda_id) REFERENCES sodas (id) ON DELETE CASCADE,
      FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE,

  quantity INT NOT NULL CHECK (quantity > 0),
  UNIQUE(cart_id, soda_id)
);
-- keepId INT NOT NULL,
-- vaultId INT NOT NULL,
-- FOREIGN KEY (vaultId) REFERENCES vaults (id) ON DELETE CASCADE,
-- FOREIGN KEY (keepId) REFERENCES keeps (id) ON DELETE CASCADE,
-- FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE

CREATE TABLE orders (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  user_id INT NOT NULL,
  cart_id INT NOT NULL,
  creatorId VARCHAR(255) NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  status VARCHAR(20) DEFAULT 'Pending', -- e.g., Pending, Shipped, Delivered

  FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
  FOREIGN KEY (creatorId) REFERENCES accounts(id) ON DELETE CASCADE
);


INSERT INTO sodas(
`name`,
`description`,
`price`,
`stock`,
`image_url`,
`creatorId`)
VALUES
('Coca-Cola', 'Classic Coca-Cola soda', 1.50, 100, 'https://example.com/coca-cola.jpg', '6691cd264de80d398f94368a');





-- INSERT INTO `vaultKeep`(
--   `vaultId`,
--   `keepId`,
--   `creatorId`
-- ) VALUES(244, 209, "66d109c1258b754bca428053");
